<?php

use App\Kernel;

/**
 * Load the autoloader and the Symfony Runtime component.
 * This file is automatically generated by Composer.
 */
require_once dirname(__DIR__).'/vendor/autoload_runtime.php';

/*
 * Set the default timezone for the application.
 * This ensures all date and time operations use the same reference.
 */
date_default_timezone_set('Europe/Paris');

/*
 * The main entry point function.
 *
 * @return Kernel A new instance of the application kernel.
 * @var array $context Contains all environment variables (from .env files).
 */
return function (array $context) {
    /*
     * The $context array contains variables defined in your .env file
     * like APP_ENV and APP_DEBUG.
     */
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
